Workshop 1 & 2 - notevenalex
nodo-eafit-frontend/frontend-20232-f03-workshop pull request #6
Opened 2023-09-27 00:21 UTC by notevenalex

### **News Paper with HTML and CSS:**

**Acceptance Criteria:**

- [ ] It must be a responsive page [Mobile, Tablet, Desktop].
- [ ] If you can use a SASS preprocessor or others (Recommended).
- [ ] You must use good semantics in the HTML tags.

### **Implement your own magazine design**

**Acceptance Criteria:**

- [ ] You have to use a preprocessor like sass or others.
- [ ] Organize your styles in separate files according to responsibility.
- [ ] You can't have burned code.

2023-10-10 02:45 UTC, DanteCely commented
Te falta implementar SASS 🙄

2023-10-10 23:04 UTC, notevenalex commented
> Te falta implementar SASS 🙄

Listo

2023-10-23 01:43 UTC, DanteCely requested changes

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/cooking-recipe.html
> +                <h3>con mayonesa</h3>
Se ve que hace parte del `<h2>`
Si quieres usar un salto de linea utiliza dentro del `<h2>` un `<br>`

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/cooking-recipe.html
> +                    </div>
Utiliza una lista no ordenada para los `<div class="recipe-property-container">`
[HTML `<ul> `Tag](https://www.w3schools.com/tags/tag_ul.asp)

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/cooking-recipe.html
> +                </p>
Utiliza una lista ordenada para los párrafos.
[HTML `<ol>` Tag](https://www.w3schools.com/tags/tag_ol.asp)

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/cooking-recipe.html
> +                </p>
Utiliza una lista no ordenada para los párrafos.
[HTML `<ul>` Tag](https://www.w3schools.com/tags/tag_ul.asp)

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/sass-folder/styles.scss
> +  background-color: "$beige-1";
```suggestion
  background-color: $beige-1;
```
No uses `""` para las variables

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/sass-folder/styles.scss
> +@import "../variables.scss";
Reorganiza las variables, reset y demás archivos sass en una carpeta sass

2023-10-23 01:43 UTC, DanteCely commented on notevenalex/book-recipe/sass-folder/styles.scss
> +  background-color: var(--red);
Variable tiene que ser variable sass

2023-11-06 23:19 UTC, merged